# Generated by Django 3.1.2 on 2020-10-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('query_date', models.DateTimeField(auto_now_add=True)),
                ('processed_count', models.IntegerField(default=0)),
                ('mark', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Query Info',
                'db_table': 'query_info',
            },
        ),
    ]
