# Generated by Django 3.1.2 on 2020-10-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryinfo',
            name='mark',
            field=models.BooleanField(default=True),
        ),
    ]
