# Generated by Django 3.1.2 on 2020-10-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201022_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryinfo',
            name='mark',
            field=models.BooleanField(default=False),
        ),
    ]
